AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda do projeto URL Shortener - Versao Vazia para Infra

Parameters:
  ProjectName:
    Type: String
  Environment:
    Type: String
    AllowedValues: [dev, prod]
  LambdaMemory:
    Type: Number
    Default: 512
  LambdaTimeout:
    Type: Number
    Default: 10
  ArtifactBucket:
    Type: String
  ArtifactKey:
    Type: String

Resources:
  UrlShortenerLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-${Environment}-handler"
      Runtime: python3.9
      Handler: index.handler
      MemorySize: !Ref LambdaMemory
      Timeout: !Ref LambdaTimeout
      Role: 
        Fn::ImportValue: !Sub "${ProjectName}-${Environment}-LambdaExecutionRoleArn"
      Code:
        ZipFile: |
          def handler(event, context):
              return {'statusCode': 200, 'body': 'Lambda Vazia para Infra'}
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          TABLE_NAME: 
            Fn::ImportValue: !Sub "${ProjectName}-${Environment}-DynamoTable"
      Tags:
        - Key: project
          Value: !Ref ProjectName
        - Key: environment
          Value: !Ref Environment

  LambdaDynamoPermission:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "${ProjectName}-${Environment}-dynamo-policy"
      Roles:
        - Fn::ImportValue: !Sub "${ProjectName}-${Environment}-LambdaExecutionRoleName"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:PutItem
              - dynamodb:GetItem
              - dynamodb:UpdateItem
              - dynamodb:Query
            Resource: 
              - Fn::ImportValue: !Sub "${ProjectName}-${Environment}-DynamoTableArn"
              - !Sub 
                - "${TableArn}/index/originalUrl-index"
                - TableArn: !ImportValue 
                    Fn::Sub: "${ProjectName}-${Environment}-DynamoTableArn"

Outputs:
  LambdaArn:
    Description: ARN da Lambda
    Value: !GetAtt UrlShortenerLambda.Arn
    Export:
      Name: !Sub "${ProjectName}-${Environment}-LambdaArn"