AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda do projeto URL Shortener - Versao Java Final

Parameters:
  ProjectName:
    Type: String
  Environment:
    Type: String
    AllowedValues: [dev, prod]
  LambdaMemory:
    Type: Number
    Default: 512
  LambdaTimeout:
    Type: Number
    Default: 20  # Java precisa de um pouco mais de tempo para o Cold Start
  ArtifactBucket:
    Type: String
  ArtifactKey:
    Type: String

Resources:
  UrlShortenerLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-${Environment}-handler"
      Runtime: java17    # Alterado para suportar seu backend Java
      Handler: com.asantanadev.urlshortener.Handler::handleRequest # Ajuste para o seu path real do Java
      MemorySize: !Ref LambdaMemory
      Timeout: !Ref LambdaTimeout
      Role: 
        Fn::ImportValue: !Sub "${ProjectName}-${Environment}-LambdaExecutionRoleArn"
      Code:
        S3Bucket: !Ref ArtifactBucket # Agora ele busca o arquivo de 15MB no S3
        S3Key: !Ref ArtifactKey
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          TABLE_NAME: 
            Fn::ImportValue: !Sub "${ProjectName}-${Environment}-DynamoTable"
      Tags:
        - Key: project
          Value: !Ref ProjectName
        - Key: environment
          Value: !Ref Environment

  LambdaDynamoPermission:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "${ProjectName}-${Environment}-dynamo-policy"
      Roles:
        - Fn::ImportValue: !Sub "${ProjectName}-${Environment}-LambdaExecutionRoleName"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:PutItem
              - dynamodb:GetItem
              - dynamodb:UpdateItem
              - dynamodb:Query
            Resource: 
              - Fn::ImportValue: !Sub "${ProjectName}-${Environment}-DynamoTableArn"
              - !Sub 
                - "${TableArn}/index/originalUrl-index"
                - TableArn: !ImportValue 
                    Fn::Sub: "${ProjectName}-${Environment}-DynamoTableArn"

Outputs:
  LambdaArn:
    Description: ARN da Lambda
    Value: !GetAtt UrlShortenerLambda.Arn
    Export:
      Name: !Sub "${ProjectName}-${Environment}-LambdaArn"