AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Master Stack do projeto URL Shortener.
  Cria toda a infraestrutura principal (sem DNS):
  - Infra base (IAM, Logs)
  - DynamoDB
  - Lambda
  - API Gateway

Parameters:
  ProjectName:
    Type: String
    Description: Nome do projeto (ex: url-shortener)

  Environment:
    Type: String
    AllowedValues:
      - dev
      - prod
    Description: Ambiente de deploy

  ArtifactsBucket:
    Type: String
    Description: Bucket S3 onde estão os templates dos módulos

Resources:

  # ======================================
  # INFRA BASE (IAM + LOGS)
  # ======================================
  InfraBaseStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${ArtifactsBucket}/modules/infra-base.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment

  # ======================================
  # DATABASE (DYNAMODB)
  # ======================================
  DatabaseStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: InfraBaseStack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${ArtifactsBucket}/modules/database.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment

  # ======================================
  # LAMBDA
  # ======================================
  LambdaStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: DatabaseStack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${ArtifactsBucket}/modules/lambda.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        LambdaMemory: 512
        LambdaTimeout: 10
        ArtifactBucket: !Ref ArtifactsBucket
        ArtifactKey: "lambda/url-shortener.jar"

  # ======================================
  # API GATEWAY
  # ======================================
  ApiStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: LambdaStack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${ArtifactsBucket}/modules/api.yaml"
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment

Outputs:
  ApiGatewayDomainName:
    Description: "Domain name real do API Gateway para uso no DNS"
    Value: !GetAtt ApiStack.Outputs.ApiGatewayDomainName
    Export:
      Name: !Sub "${AWS::StackName}-ApiGatewayDomainName"

  ApiGatewayHostedZoneId:
    Description: "Hosted Zone ID real do API Gateway para uso no DNS"
    Value: !GetAtt ApiStack.Outputs.ApiGatewayHostedZoneId
    Export:
      Name: !Sub "${AWS::StackName}-ApiGatewayHostedZoneId"

